language: node_js

node_js: 
  - node

sudo: false

install:
  - npm install -q --no-color --no-progress
  - npm install -g codecov
  
script: 
  - npm test
  - codecov

after success: 
  - npm run coverage
